#!/bin/sh

###########################################
### NZBGET SCAN SCRIPT                  ###

# Print test message.
#
# This is a test script. It prints one message to log. Here in the
# long description we could write instructions for user.
#
# The long description can have multiple paragraphs when needed. Like
# this one.

### NZBGET SCAN SCRIPT                  ###
###########################################

echo "scan script test"