---
###############################################################################
# Configure Services
###############################################################################
# Service only supports restarts for configuration reloading.
#
# Filetree returns a dict (instead of a list of dict) for one element. Use
# query to guarantee a list result.
#
# Reference:
# * https://nzbgetcom.github.io/#debian-repository
# * https://nzbget.com

- name: '{{ "Config | filesystem | set " ~ nzbget__cfg._cfg_dest }}'
  ansible.builtin.template:
    src: '{{ nzbget__cfg._cfg_file }}'
    dest: '{{ nzbget__cfg._cfg_dest }}'
    owner: '{{ nzbget__srv._user }}'
    group: '{{ nzbget__srv._group }}'
    mode: '0640'  # Default 0644, passwords.

- name: 'Config | filetree | deploy managed files'
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ nzbget__cfg._scripts_dest ~ "/" ~ item.path }}'
    owner: '{{ nzbget__srv._user }}'
    group: '{{ nzbget__srv._group }}'
    mode: '0755'
  loop: '{{ query("community.general.filetree", nzbget__cfg._scripts_dir) }}'
  loop_control:
    label: '{{ item.path }}'
  when: item.state == 'file'
  register: nzbget__local

- name: 'Config | filesystem | query remote files'
  ansible.builtin.find:
    paths: '{{ nzbget__cfg._scripts_dest }}'
    file_type: 'file'
    recurse: true
  register: nzbget__remote

- name: 'Config | filesystem | remove unmanaged files'
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: 'absent'
  loop: '{{ nzbget__remote.files }}'
  loop_control:
    label: '{{ item.path }}'
  when: >
    item.path not in nzbget__local.results | map(attribute='dest') | list
