---
###############################################################################
# Configure Services
###############################################################################
# NZBGet requires nzbget_script_dir, /var/lib/nzbget/nzbget.conf to start.
# Service only supports restarts for configuration reloading.
#
# Decision: nzbget_script_dir is one directory - explicitly restricted to a
#     single directory instead of a list of directories in original config.
#
# New nzbget.conf options must be manually added to the template and role
# default templates.
#
# Reference:
# * https://nzbgetcom.github.io/#debian-repository
# * https://nzbget.com

- name: 'Config | lock NZBGet package user'
  when: _nzbget_srv_user.raw != 'nzbget'
  ansible.builtin.user:
    name: 'nzbget'
    password: '!'
    password_lock: true

# Permissions determined from vanilla service start
- name: 'Config | manage config directories'
  ansible.builtin.file:
    path: '{{ item.path }}'
    owner: '{{ _nzbget_srv_user.role_uid }}'
    group: '{{ _nzbget_srv_group.role_gid }}'
    mode: '{{ item.mode }}'
    recurse: false
    state: 'directory'
  become: true
  changed_when: false  # https://github.com/ansible/ansible/issues/32636
  loop:
    - path: '{{ nzbget_role_install_dir }}'
      mode: '2750'
    - path: '{{ _nzbget_cfg_main_dir.raw }}'
      mode: '{{ _nzbget_srv_media_perms_folder.raw }}'
    - path: '{{ _nzbget_cfg_inter_dir.raw }}'
      mode: '{{ _nzbget_srv_media_perms_folder.raw }}'
    - path: '{{ _nzbget_cfg_nzb_dir.raw }}'
      mode: '{{ _nzbget_srv_media_perms_folder.raw }}'
    - path: '{{ _nzbget_cfg_queue_dir.raw }}'
      mode: '{{ _nzbget_srv_media_perms_folder.raw }}'
    - path: '{{ _nzbget_cfg_temp_dir.raw }}'
      mode: '0755'
    - path: '{{ _nzbget_cfg_web_dir.raw }}'
      mode: '0755'
    - path: '{{ _nzbget_cfg_script_dir.raw }}'
      mode: '0755'
    - path: '{{ _nzbget_cfg_lock_file.role_dest }}'
      mode: '{{ _nzbget_srv_media_perms_folder.raw }}'
    - path: '{{ _nzbget_cfg_log_file.role_dest }}'
      mode: '{{ _nzbget_srv_media_perms_folder.raw }}'
    - path: '{{ _nzbget_cfg_config_template.role_dest }}'
      mode: '0755'
    - path: '{{ _nzbget_cfg_cert_store.role_dest }}'
      mode: '0755'
  loop_control:
    label: '{{ item.path }}'

- name: 'Config | manage media directories'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ _nzbget_srv_user.role_uid }}'
    group: '{{ _nzbget_srv_group.role_gid }}'
    mode: '{{ _nzbget_srv_media_perms_folder.raw }}'
    recurse: true
    state: 'directory'
  become: true
  become_user: '{{
      _nzbget_srv_user.raw
      if _nzbget_srv_user_data_manage_enable.raw else
      "root"
    }}'
  loop:
    - '{{ _nzbget_cfg_dest_dir.raw }}'

# yamllint disable rule:line-length
- name: 'Config | set media file permissions'
  when: _nzbget_srv_media_set_perms_file_enable.raw
  ansible.builtin.shell: >-
    find '{{ item }}'
    -type f
    -exec chmod {{ _nzbget_srv_media_perms_file.raw }} {};
      chown {{ _nzbget_srv_user.role_uid }}:{{ _nzbget_srv_group.role_gid }} {} \;
  changed_when: false
  loop:
    - '{{ _nzbget_cfg_main_dir.raw }}'
    - '{{ _nzbget_cfg_nzb_dir.raw }}'
    - '{{ _nzbget_cfg_queue_dir.raw }}'
    - '{{ _nzbget_cfg_lock_file.role_file }}'
    - '{{ _nzbget_cfg_log_file.role_file }}'
    - '{{ _nzbget_cfg_dest_dir.raw }}'
    - '{{ _nzbget_cfg_inter_dir.raw }}'

- name: 'Config | extension scripts'
  when: _nzbget_srv_scripts_source.raw | length > 0
  block:
    - name: 'Config | extension scripts | copy'
      ansible.posix.synchronize:
        src: '{{ _nzbget_srv_scripts_source.role_src }}'
        dest: '{{ _nzbget_cfg_script_dir.raw }}'
        delete: true
        recursive: true
        archive: false
        checksum: true

    # yamllint disable rule:line-length
    - name: 'Config | extension scripts | set permissions'
      ansible.builtin.shell: |
        chown -R {{ _nzbget_srv_user.role_uid }}:{{ _nzbget_srv_group.role_gid }} '{{ _nzbget_cfg_script_dir.raw }}' &&
        find '{{ _nzbget_cfg_script_dir.raw }}' -type d -exec chmod 2750 {} \; &&
        find '{{ _nzbget_cfg_script_dir.raw }}' -type f -exec chmod 0755 {} \;
      changed_when: false

- name: 'Config | set nzbget configuration'
  ansible.builtin.template:
    src: 'nzbget.conf.j2'
    dest: '{{ nzbget_role_config }}'
    owner: '{{ _nzbget_srv_user.role_uid }}'
    group: '{{ _nzbget_srv_group.role_gid }}'
    mode: '0640'

- name: 'Prep | set NZBGet service drop-in'
  when: _nzbget_srv_user.raw != 'nzbget' or _nzbget_srv_group.raw != 'nzbget'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.systemd'
  vars:
    systemd_daemon_reload_enable: true
    systemd_services:
      - name: 'nzbget'
        state: 'present'
        drop_in: true
        service: {}
        exec:
          user: '{{ _nzbget_srv_user.raw }}'
          group: '{{ _nzbget_srv_group.raw }}'

- name: 'Config | flush handlers'
  ansible.builtin.meta: 'flush_handlers'
