---
###############################################################################
# Prep
###############################################################################
# NZBGet install from deb packages are categorically broken. There are no
# debconf options.
#
# Prepare system for install by creating user/group for service.
#
# Do not remove the default (NZBGet) user as this will put APT in a broken
# state. Instead ensure the account is fully locked.
#
# Reference:
# * https://nzbget.com

- name: 'Prep | assert data locations are not in install paths'
  ansible.builtin.assert:
    quiet: true
    that:
      - not _nzbget_cfg_dest_dir.raw.startswith(
        nzbget_role_install_dir)
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │    Data storage should not be in the same location as install.    │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ Install: {{ nzbget_role_install_dir }}
      │
      │ nzbget_cfg_dest_dir: {{ _nzbget_cfg_dest_dir.raw }}

- name: 'Prep | manage users'
  when: _nzbget_srv_create_user.raw
  ansible.builtin.include_role:
    name: 'r_pufky.deb.users'
    tasks_from: 'role_account_add.yml'
  vars:
    users_role_user: '{{ nzbget_role_user }}'
    users_role_group: '{{ nzbget_role_group }}'

- name: 'Prep | enumerate system user {{ _nzbget_srv_user.raw }}'
  ansible.builtin.user:
    name: '{{ _nzbget_srv_user.raw }}'
  check_mode: true
  changed_when: false
  register: _nzbget_srv_user_query

- name: 'Prep | parse system user UID/GID'
  ansible.builtin.set_fact:
    _nzbget_srv_user: '{{
        _nzbget_srv_user |
        combine({"_uid": _nzbget_srv_user_query.uid})
      }}'
    _nzbget_srv_group: '{{
        _nzbget_srv_group |
        combine({"_gid": _nzbget_srv_user_query.group})
      }}'
