---
# yamllint disable rule:line-length
###############################################################################
# Prep NZBGet
###############################################################################
# NZBGet install from deb packages are categorically broken. There are no
# debconf options.
#
# Prepare system for install by creating user/group for service, add drop-in
# for user/group service override, and sanitize (standardize with default
# values if not set) NZBGet configuration.
#
# Do not remove the default (NZBGet) user as this will put APT in a broken
# state. Instead ensure the account is fully locked.
#
# Generates:
#   _nzbget_news_servers: list of dict - sanitized nzbget_news_servers
#   _nzbget_categories: list of dict - sanitized nzbget_categories
#   _nzbget_rss_feeds:  list of dict - sanitized nzbget_rss_feeds
#   _nzbget_tasks: list of dict - sanitized nzbget_tasks
#
# Reference:
# * https://nzbget.com

# TODO(role): add account lock for non-standard user.
- name: 'Prep | manage users'
  when: nzbget_create_user
  ansible.builtin.include_role:
    name: 'r_pufky.srv.users'
    tasks_from: 'role_account_add.yml'
  vars:
    users_role_group: '{{ nzbget_role_group }}'
    users_role_user: '{{ nzbget_role_user }}'

- name: 'Prep | sanitize nzbget_news_servers'
  when: nzbget_news_servers | length > 0
  ansible.builtin.set_fact:
    _nzbget_news_servers: '{{ _nzbget_news_servers | default([]) + [nzbget_role_template_news_servers | combine(item)] }}'
  loop: '{{ nzbget_news_servers }}'

- name: 'Prep | sanitize nzbget_categories'
  when: nzbget_categories | length > 0
  ansible.builtin.set_fact:
    _nzbget_categories: '{{ _nzbget_categories | default([]) + [nzbget_role_template_categories | combine(item)] }}'
  loop: '{{ nzbget_categories }}'

- name: 'Prep | sanitize nzbget_rss_feeds'
  when: nzbget_rss_feeds | length > 0
  ansible.builtin.set_fact:
    _nzbget_rss_feeds: '{{ _nzbget_rss_feeds | default([]) + [nzbget_role_template_rss_feeds | combine(item)] }}'
  loop: '{{ nzbget_rss_feeds }}'

- name: 'Prep | sanitize nzbget_tasks'
  when: nzbget_tasks | length > 0
  ansible.builtin.set_fact:
    _nzbget_tasks: '{{ _nzbget_tasks | default([]) + [nzbget_role_template_tasks | combine(item)] }}'
  loop: '{{ nzbget_tasks }}'
