---
###############################################################################
# Pre Execution Tasks
###############################################################################
# Only use data annotations in role after merging role, defaults, runtime data.
# Service may not exist if first install.
#
# Reference:
# * https://nzbget.com

- name: 'Prep | fact | record start time'
  ansible.builtin.set_fact:
    nzbget__srv: "{{ nzbget___release | r_pufky.data.v3(

        _start=now(utc=True, fmt='%Y-%m-%dT%H%M%S'),
        _user=nzbget_srv_user,
        _group=nzbget_srv_group,
      ) }}"
    nzbget__cfg: "{{ {} | r_pufky.data.v3(

        _file=nzbget_cfg_file,
        _scripts_d=nzbget_cfg_scripts_d | regex_replace('\\/$', ''),
      ) }}"

- name: 'Prep | assert | service user is not nzbget'
  ansible.builtin.assert:
    quiet: true
    that:
      - nzbget__srv._user != 'nzbget'
      - nzbget__srv._group != 'nzbget'
    fail_msg: |

      ✘ NZBGet service user/group must NOT be 'nzbget'.
      Create a custom user before executing this role or use 'media' to
      automatically create a service user for NZBGet.

      nzbget_srv_user: {{ nzbget__srv._user }}
      nzbget_srv_group: {{ nzbget__srv._group }}

- name: 'Prep | assert | config enabled and source defined'
  when: nzbget_flg_config
  ansible.builtin.assert:
    quiet: true
    that:
      - nzbget__cfg._file | length > 0
    fail_msg: |

      ✘ Config source not set.
      Config source enabled but no config source defined.

      nzbget_flg_config: {{ nzbget_flg_config }}
      nzbget_cfg_file: {{ nzbget__cfg._file }}

- name: '{{ "Prep | account | query user " ~ nzbget__srv._user }}'
  ansible.builtin.command: '{{ "id " ~ nzbget__srv._user }}'
  failed_when: false
  register: nzbget__cfg_check
  changed_when: nzbget__cfg_check.rc > 0

- name: '{{ "Prep | account | query group " ~ nzbget__srv._group }}'
  ansible.builtin.command: '{{ "groups " ~ nzbget__srv._group }}'
  failed_when: false
  register: nzbget__group_check
  changed_when: nzbget__group_check.rc > 0

- name: '{{ "Prep | account | create group " ~ nzbget__srv._group }}'
  when: nzbget__group_check.rc != 0
  ansible.builtin.group:
    gid: '{{ nzbget___group.gid }}'
    name: '{{ nzbget___group.name }}'
    state: 'present'

- name: '{{ "Prep | account | create user " ~ nzbget__srv._user }}'
  when: nzbget__cfg_check.rc != 0
  ansible.builtin.user:
    name: '{{ nzbget___user.name }}'
    group: '{{ nzbget___user.group }}'
    uid: '{{ nzbget___user.uid }}'
    shell: '{{ nzbget___user.shell }}'
    home: '{{ nzbget___user.home }}'
    create_home: '{{ nzbget___user.create_home }}'
    password: '{{ nzbget___user.password }}'
    password_lock: '{{ nzbget___user.password_lock }}'
    update_password: '{{ nzbget___user.update_password }}'
    expires: '{{ nzbget___user.expires }}'
    system: '{{ nzbget___user.system }}'

# Pre-existing users may have a different UID/GID/Home.
- name: '{{ "Prep | account | enumerate " ~ nzbget__srv._user }}'
  ansible.builtin.user:
    name: '{{ nzbget__srv._user }}'
  check_mode: true
  changed_when: false
  register: nzbget__cfg_query

- name: 'Prep | fact | parse service UID/GID'
  ansible.builtin.set_fact:
    nzbget__cfg: "{{ nzbget__cfg | r_pufky.data.v3(

        _uid=nzbget__cfg_query.uid,
        _gid=nzbget__cfg_query.group,
      ) }}"

# Render configuration locally and resolve configured service paths.
- name: 'Prep | fact | resolve nzbget.conf'
  ansible.builtin.set_fact:
    nzbget__srv: "{{ nzbget__srv | r_pufky.data.v3(

        _tmpl_cfg=lookup(
          'ansible.builtin.template',
          nzbget__cfg._file
          if nzbget__cfg._file | length > 0 else
          'templates/default/nzbget.conf'
        ),
      ) }}"

- name: 'Prep | fact | parse directories'
  ansible.builtin.set_fact:
    nzbget__srv: "{{ nzbget__srv | r_pufky.data.v3(

        _cfg_main_d=(
          nzbget__srv._tmpl_cfg |
          regex_search('^MainDir=(.*)$', '\\1', multiline=True) |
          default([''], true) | first
        ),
        _cfg_dest_d=(
          nzbget__srv._tmpl_cfg |
          regex_search('^DestDir=(.*)$', '\\1', multiline=True) |
          default([''], true) | first
        ),
        _cfg_inter_d=(
          nzbget__srv._tmpl_cfg |
          regex_search('^InterDir=(.*)$', '\\1', multiline=True) |
          default([''], true) | first
        ),
        _cfg_nzb_d=(
          nzbget__srv._tmpl_cfg |
          regex_search('^NzbDir=(.*)$', '\\1', multiline=True) |
          default([''], true) | first
        ),
        _cfg_queue_d=(
          nzbget__srv._tmpl_cfg |
          regex_search('^QueueDir=(.*)$', '\\1', multiline=True) |
          default([''], true) | first
        ),
        _cfg_temp_d=(
          nzbget__srv._tmpl_cfg |
          regex_search('^TempDir=(.*)$', '\\1', multiline=True) |
          default([''], true) | first
        ),
        _cfg_web_d=(
          nzbget__srv._tmpl_cfg |
          regex_search('^WebDir=(.*)$', '\\1', multiline=True) |
          default([''], true) | first
        ),
        _cfg_script_d=(
          nzbget__srv._tmpl_cfg |
          regex_search('^ScriptDir=(.*)$', '\\1', multiline=True) |
          default([''], true) | first
        ),
      ) }}"

- name: 'Prep | systemd | stop nzbget.service'
  ansible.builtin.systemd:
    name: 'nzbget.service'
    state: 'stopped'
  failed_when: false
