---
# yamllint disable rule:line-length
collections: []

roles:
  - name: 'r_pufky.srv.apt'  # https://github.com/r-pufky/ansible_collection_srv
  - name: 'r_pufky.srv.systemd'  # https://github.com/r-pufky/ansible_collection_srv
  - name: 'r_pufky.srv.users'  # https://github.com/r-pufky/ansible_collection_srv
