---
###############################################################################
# NZBGet Handlers
###############################################################################

- name: 'Handlers | restart nzbget'
  ansible.builtin.systemd:
    name: 'nzbget'
    enabled: true
    daemon_reload: true
    state: 'restarted'
