---
###############################################################################
# Default
###############################################################################
# Default role is applied correctly.
#
# Tests:
# * nzbget.conf deployed.
# * scripts/ sourced correctly.
# * Permissions propagated to all directories.
# * Service is active and running.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        nzbget_flg_config: true
        nzbget_flg_perms: true
        nzbget_cfg_file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/templates/default/nzbget.conf"
          }}'
        nzbget_cfg_scripts_d: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~ "/files"
          }}'
platforms:
  - name: 'nzbget-default'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    published_ports:
      - '6789:6789/tcp'
    pre_build_image: true
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'converge'
    - 'verify'
    - 'destroy'
