---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | /var/lib/nzbget/nzbget.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | /var/lib/nzbget/nzbget.conf'
        test_src: 'files/nzbget.conf'
        test_file: '/var/lib/nzbget/nzbget.conf'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0640'
        test_diff: true
