---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: '{{ "Verify | test | " ~ nzbget___app._cfg }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'copy.yml'
      vars:
        test_name: '{{ "Verify | test | " ~ nzbget___app._cfg }}'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/templates/default/nzbget.conf"
          }}'
        test_file: '{{ nzbget___app._cfg }}'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0640'
        test_diff: true

    - name: '{{ "Verify | test | " ~ nzbget___app._scripts_d }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'copy.yml'
      vars:
        test_name:
          '{{ "Verify | test | " ~ nzbget___app._scripts_d }}'
        test_src: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~
            "/files/post_processing"
          }}'
        test_file:
          '{{ nzbget___app._scripts_d ~ "/post_processing" }}'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0750'
        test_diff: true
