---
- name: 'Default | verify | service'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | service | gather service status'
      ansible.builtin.service_facts:

    # NZBGet will fail if configuration is bad (r_pufky.deb.systemd)
    - name: 'Default | verify | service | assert nzbget.service active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"nzbget.service" in ansible_facts.services'
          - 'ansible_facts["services"]["nzbget.service"]["state"] == "running"'
        fail_msg: '✘ nzbget.service should be enabled and running.'

    - name: 'Default | verify | service | /var/lib/nzbget/nzbget.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Default | verify | service | /var/lib/nzbget/nzbget.conf'
        test_src: 'files/nzbget.conf'
        test_file: '/var/lib/nzbget/nzbget.conf'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0640'
