---
###############################################################################
# Categories
###############################################################################

# Available categories for WebUI.
#
# nzbget_cfg_categories:
#     list of dict - NZB category definitions
#   - id: int - Category ID starting at 1; categories must be defined sequently
#           without holes otherwise NZBGet will not properly read config.
#     name: str - Category name; passed to post-processing script and can be
#           used by it to perform category specific processing.
#     dest_dir: str - Destination directory; if empty nzbget_cfg_dest_dir is
#           used, if nzbget_cfg_append_category_dir=true a subdirectory with
#           category name within destination directory is created.
#         Default: '' (use nzbget_cfg_dest_dir).
#     unpack: bool - Unpack downloaded NZB files; see nzbget_cfg_unpack
#         Default: True.
#     extensions: list of str - List of extension scripts for this category,
#           located in nzbget_cfg_script_dir. See nzbget_cfg_extensions.
#
#           Reference:
#           * https://nzbget.com/documentation/extension-scripts/.
#         Default: [] (no extensions).
#     aliases: list of str - Match NZB site categories to your own#
#          Special Case:
#            *?: Wildcard and pattern matching allowed.
#         Default: [] (no aliases).
#
# nzbget_cfg_categories:
#   - id: 1
#     name: 'Movies'
#     dest_dir: ''
#     unpack: true
#     extensions: ['Move.sh', 'Email.py']
#     aliases: ['TV - HD', 'TV*']
#   - id: 2
#     name: 'Series'
#
# Default:
#   - id: 1
#     name: 'Movies'
#   - id: 2
#     name: 'Series'
#   - id: 3
#     name: 'Music'
#   - id: 4
#     name: 'Software'
nzbget_cfg_categories:
  - id: 1
    name: 'Movies'
  - id: 2
    name: 'Series'
  - id: 3
    name: 'Music'
  - id: 4
    name: 'Software'
