---
###############################################################################
# Incoming NZBs
###############################################################################

# Create subdirectory with category name in nzbget_cfg_dest_dir?
#
# Default: True.
nzbget_cfg_append_category_dir: true

# Check nzbget_cfg_nzb_dir interval for new NZB files (seconds).
#
# Values:
#   0: Disabled.
#
# Default: 5.
nzbget_cfg_nzb_dir_interval: 5

# Minimum NZB file age to add to queue (seconds).
#
# Safety interval to prevent loading files not completely saved to disk (e.g.
# still being downloaded in web-browser).
#
# Default: 60.
nzbget_cfg_nzb_dir_file_age: 60

# Check for duplicate titles?
#
# nzbget_cfg_health_check must be delete, park, or none.
#
# Duplicates determined (NZB not added):
# * History contains the same title with success status.
# * Download queue already contains the same title; NZB file added to queue for
#   backup if first file fails.
# * NZB file contains duplicate entries, helps to find errors in bad NZB files.
#
# Same title means the NZB file name is same or the duplicate key is same.
# Duplicate keys are set by fetching from RSS feeds using title identifier
# fields provided by RSS provider (IMDB ID or RAGE ID/season/episode).
#
# Duplicates only downloaded if downloading fails. All remaining duplicates
# deleted on success.
#
# Default: True.
#
# Reference:
# * https://nzbget.com/documentation/rss/
nzbget_cfg_dupe_check: true
