---
###############################################################################
# News Servers
###############################################################################
# Ansible has 'port' as RESERVED keyword, use srv_port instead.
#
# Reference:
# * https://github.com/ansible/ansible/pull/69585

# NZB News Servers to use.
#
# nzbget_cfg_news_servers:
#     list of dict - NZB news server definitions.
#   - id: int - Server ID starting at 1; servers must be defined sequently
#           without holes otherwise NZBGet will not properly read config. ID
#           does not affect priority level.
#     active: bool - Use this news server; servers at higher levels are only
#           used if at least one server below a given level is enabled.
#         Default: True.
#     name: str - News server friendly name.
#         Default: ''.
#     level: int - Priority level of news server; all servers are tried at
#           priority level before trying lower levels. Fill servers should be
#           below major servers. Multiple servers may have the same level.
#         Values:
#            0: Highest priority (default).
#           99: Lowest priority.
#         Default: 0.
#     optional: bool - Mark server as optional and non-reliable; ignore server
#           if a connection fails and immediately go with higher level servers.
#         Default: False.
#     group: int - Server group; downloads failing on one news server, will not
#           try other servers from the same group.
#         Values:
#            0: No group defined (default).
#            1: Min group.
#           99: Max group.
#         Default: 0 (no group).
#     srv_host: str - Server hostname.
#     srv_port: int - Server port.
#         Values:
#             563: Typical for secure connections (default).
#             443: Rare secure connections.
#             119: Typical for unsecure connections.
#              80: Rare unsecure connections.
#           65535: Max port.
#         Default: 563.
#     encryption: bool - Use encrypted server connection (TLS/SSL); ensure the
#           correct port is set.
#         Default: True.
#     username: str - News server username.
#     password: str - News server password.
#     join_group: bool - Enable when server requires 'Join Group' command
#         Default: False.
#     cipher: str - Cipher to use for encrypted server connections
#           unsupported ciphers will cause TLS handshake errors. Invalid
#           ciphers will generate 'Could not select cipher for TLS'.
#
#           Reference:
#           * https://nzbget.com/documentation/choosing-cipher/
#         Values:
#                 '': Automatic cipher selection (default).
#           {CIPHER}: Manual cipher selection
#         Default: '' (automatic).
#     connections: int - Max simultaneous connections to this server (0-999)
#         Default: 8.
#     retention: int - Server retention time (days); articles exceeding
#           retention are not tried and instead considered failed.
#         Special Case:
#           0: Disables retention check (default).
#         Default: 0.
#     cert_verification: str - Certificate verification level.
#         Values:
#              none: Disable signing check, disable hostname check.
#           minimal: Enable signing check, disable hostname check.
#            strict: Enable signing check, enable hostname check (default).
#         Default: 'strict'.
#     ip_version: str - IP protocol version to use.
#         Values:
#           auto: Use either IPv4 or IPv6 (disable).
#           ipv4: IPv4 only.
#           ipv6: IPv6 only.
#         Default: 'auto'.
#     notes: str - User comments on server
#         Default: ''.
#
# nzbget_cfg_news_servers:
#   - id: 1
#     active: true
#     name: ''
#     level: 0
#     optional: false
#     group: 0
#     srv_host: 'news.example.com'
#     srv_port: 563
#     encryption: true
#     username: 'user'
#     password: 'pass'
#     join_group: false
#     cipher: ''
#     connections: 4
#     retention: 0
#     cert_verification: 'strict'
#     ip_version: 'auto'
#     notes: ''
#   - id: 2
#     level: 1
#     srv_host: 'alt.example.com'
#     username: 'user'
#     password: 'pass'
#
# Default: [].
nzbget_cfg_news_servers: []
