---
###############################################################################
# Scheduler
###############################################################################

# NZB Scheduled Tasks.
#
# nzbget_cfg_tasks:
#     list of dict - NZB scheduled task definitions.
#   - id: int - Task ID starting at 1; tasks must be defined sequently without
#           holes otherwise NZBGet will not properly read config.
#     time: list of str - Time to execute commands.
#          Values:
#            {HH:MM}: 24 hour time.
#             {*:MM}: Every hour at minute.
#                  *: At startup.
#     week_days: list of str or int - Week days to execute commands.
#          Special Case:
#            1: Monday.
#          Values:
#              #: Day.
#            #-#: Inclusive range of days.
#     command: str - Command to be executed.
#          Values:
#                 PauseDownload: Pause download.
#               UnpauseDownload: Resume download.
#              PausePostProcess: Pause post-processing.
#            UnpausePostProcess: Resume post-processing.
#                     PauseScan: Pause scan of incoming nzb-directory.
#                   UnpauseScan: Resume scan of incoming nzb-directory.
#                  DownloadRate: Set download rate limit.
#                        Script: Execute scheduler scripts; must be written.
#                                specially for NZBGet.
#                       Process: Execute an external (any) program.
#                ActivateServer: Activate news-server.
#              DeactivateServer: Deactivate news-server.
#                     FetchFeed: Fetch RSS feed.
#     param: list of str - Required command parameters for scheduler commands
#           DownloadRate: Download rate limit (KB/sec), 0 disables.
#           Script: Scheduler scripts to execute. All scripts must be stored in
#                 nzbget_cfg_script_dir.
#
#                 Reference:
#                 * https://nzbget.com/documentation/extension-scripts/
#           Process: Absolute path to program and parameters; single quotes are
#                 automatically added to list elements, just double single
#                 quote per param documentation.
#               Special Case:
#                 ': Replace each single quotation mark (') with two single
#                    quotation marks (''):
#
#                    param: ['/bin/process.sh', "worlds''s fun"]
#
#                 Reference:
#                 * https://nzbget.com/documentation/extension-scripts/
#           ActivateServer: News server ID's or names to enabled.
#           DeactivateServer: News server ID's or names to disable.
#           FetchFeed: RSS feed ID's or names, 0 fetches all feeds.
#
# nzbget_cfg_tasks:
#   - id: 1
#     time: ['08:00']
#     week_days: ['1-7']
#     command: 'PauseDownload'
#     param: ['']
#   - id: 2
#     time: ['20:00']
#     week_days: ['1-7']
#     command: 'UnpauseDownload'
#     param: ['']
#   - id: 3
#     time: ['00:00', '06:00', '12:00', '18:00']
#     week_days: [1, 3, 5, '6-7']
#     command: 'Process'
#     param: ['/home/user/task process.sh', "world''s fun"]
#
# Default: [].
nzbget_cfg_tasks: []
